### PR TITLE
Android: circular progress example

### PR DESCRIPTION
**Pull request by m1ga**
Small example showing a circular progress bar in android: 
screenshot_20160501-153623 screenshot_20160501-153628

Full circle and arc supported

### CODE REVIEW

**Comment by hansemannn** [comment]
Can you center it?

**Comment by m1ga** [comment]
only with `layoutParams = new LayoutParams(circleRadius, circleRadius, Gravity.CENTER);` WRAP_CONTENT doesn't seem to work. But it least it looks right:

center

added a label in the middle too

**Comment by hansemannn** [comment]
So it does not work but look right? Is `WRAP_CONTENT` supposed to work?

**Comment by m1ga** [comment]
No, it works right. The other examples use fixed values too:
https://github.com/appcelerator/hyperloop-examples/blob/master/app/controllers/android/donutchart.js#L188 and have `// FIXME center this in the screen!` in the code :smile: 

I'm not sure if `WRAP_CONTENT` is supposed to work on the outer view at all cause I only draw in the canvas and don't have any real object inside

**Comment by hansemannn** [comment]
Ok, makes sense. Feel free to play around with layout-specific API's, there are probably very interesting configurations we could support. PR approved!

**Pull request merged**
